from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

RAW_EOBS_DIR = RAW_DATA_DIR / "eobs"
RAW_ISTAT_DIR = RAW_DATA_DIR / "istat"
RAW_ISPRA_DIR = RAW_DATA_DIR / "ispra"

CLIMATE_PROCESSED_DIR = PROCESSED_DATA_DIR / "climate"
CLIMATE_MAPS_DIR = CLIMATE_PROCESSED_DIR / "maps"

SAM_INTERIM_DIR = INTERIM_DATA_DIR / "sam"
SAM_PROCESSED_DIR = PROCESSED_DATA_DIR / "sam"

MODEL_INPUTS_DIR = PROCESSED_DATA_DIR / "model_inputs"

# Shock calibration and static scenario pipeline.
MAPPINGS_PROCESSED_DIR = PROCESSED_DATA_DIR / "mappings"
SHOCKS_PROCESSED_DIR = PROCESSED_DATA_DIR / "shocks"
SIMULATIONS_DIR = PROCESSED_DATA_DIR / "simulations"
DASHBOARD_DIR = PROCESSED_DATA_DIR / "dashboard"

PROVINCE_CROSSWALK_PATH = MAPPINGS_PROCESSED_DIR / "province_code_crosswalk.csv"
PROVINCE_PIR_RAW_PATH = RAW_ISPRA_DIR / "province_pir.xlsx"
PROVINCE_PIR_CLEAN_PATH = CLIMATE_PROCESSED_DIR / "province_pir_clean.csv"
HEATWAVE_INDICATORS_PATH = CLIMATE_PROCESSED_DIR / "province_heatwave_indicators.csv"
HAZARD_EXPOSURE_PATH = CLIMATE_PROCESSED_DIR / "province_hazard_exposure.csv"
ISTAT_PROVINCES_GPKG_PATH = CLIMATE_PROCESSED_DIR / "istat_provinces_2024.gpkg"
SECTOR_VULNERABILITY_PATH = SHOCKS_PROCESSED_DIR / "sector_hazard_vulnerability.csv"
SCENARIO_LIBRARY_PATH = SHOCKS_PROCESSED_DIR / "scenario_library.csv"
SHOCK_MATRIX_PATH = SHOCKS_PROCESSED_DIR / "shock_matrix.csv"
